--@exclude_input=whde.dim_marketplace_info_df
--odps sql
--********************************************************************--
--author:Ada
--create time:2024-03-03 19:37:49
--********************************************************************--


CREATE TABLE IF NOT EXISTS whde.dwd_amzn_all_orders_df(
    report_type STRING COMMENT '报告类型',
    seller_id STRING COMMENT '卖家ID',
    marketplace_id STRING COMMENT '站点ID',
    marketplace_type STRING COMMENT '站点type',
    report_id STRING COMMENT '报告ID',
    data_last_update_time DATETIME COMMENT '报告数据亚马逊生产时间（已转换成北京时间）',
    amazon_order_id STRING COMMENT '亚马逊订单编号',
    merchant_order_id STRING COMMENT '卖家订单号，卖家为订单提供的唯一标识',
    ori_purchase_time STRING COMMENT '订单创建时间',
    purchase_time DATETIME COMMENT '订单创建时间（已转换成北京时间）',
    ori_last_update_time STRING COMMENT '订单最近更新时间',
    last_update_time DATETIME COMMENT '订单最近更新时间（已转换成北京时间）',
    order_status STRING COMMENT '订单的当前状态',
    fulfillment_channel STRING COMMENT '配送方式(AFN,MFN)',
    sales_channel STRING COMMENT '首项销售渠道',
    order_channel STRING COMMENT '首项订单渠道',
    ship_service_level STRING COMMENT '订单发货服务级别',
    product_name STRING COMMENT '产品名称',
    seller_sku STRING COMMENT '卖家SKU',
    asin STRING COMMENT '子asin',
    item_status STRING COMMENT '子单当前状态',
    ordered_num BIGINT COMMENT '商品购买数量',
    currency STRING COMMENT '币种',
    item_amt DECIMAL(18,6) COMMENT '订单支付总额(商品的售价*订购的数量，不包括运费和包装费)',
    item_tax DECIMAL(18,6) COMMENT '商品价格税',
    shipping_fee DECIMAL(18,6) COMMENT '运费',
    shipping_tax DECIMAL(18,6) COMMENT '运费税',
    gift_wrap_fee DECIMAL(18,6) COMMENT '礼品包装费',
    gift_wrap_tax DECIMAL(18,6) COMMENT '礼品包装费税',
    item_promotion_discount DECIMAL(18,6) COMMENT '单品促销折扣',
    ship_promotion_discount DECIMAL(18,6) COMMENT '配送促销折扣',
    ship_city STRING COMMENT '配送城市',
    ship_state STRING COMMENT '配送州',
    ship_postal_code STRING COMMENT '配送邮编',
    ship_country STRING COMMENT '配送国家',
    promotion_ids STRING COMMENT '促销id列表',
    cpf STRING COMMENT 'cpf(具体含义暂不能确定)',
    is_business_order BIGINT COMMENT '是否商业订单（0:false;1:true)',
    purchase_order_number STRING COMMENT '购买订单编号',
    price_designation STRING COMMENT '价格标示',
    fulfilled_by STRING COMMENT '执行者(具体含义暂不能确定)',
    buyer_company_name STRING COMMENT '买家公司',
    buyer_tax_registration_country STRING COMMENT '买家税收注册国家',
    buyer_tax_registration_type STRING COMMENT '买家税收注册类型',
    is_iba BIGINT COMMENT '是否是 Amazon Business EU SARL (ABEU)（0:false;1:true)',
    order_invoice_type STRING COMMENT '订单发票类型',
    tenant_id STRING COMMENT '租户ID',
    data_src STRING COMMENT '数据源名',
    table_src STRING COMMENT '来源表名',
    data_dt STRING COMMENT '数据日期',
    etl_data_dt DATETIME COMMENT '数据加载时间'
    )
    PARTITIONED BY (ds STRING)
    STORED AS ALIORC
    TBLPROPERTIES ('comment'='亚马逊所有订单报告表')
    LIFECYCLE 365;

----亚马逊所有订单报告表开发 数据初始化
---1.时间、数据类型转换
drop table if exists temp1_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk;
create table if not exists temp1_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk
    lifecycle 1
as
select
    report_type,
    seller_id,
    marketplace_id,
    report_id,
    to_date(data_last_update_time, 'yyyy-MM-dd HH:mi:ss')data_last_update_time ,
    amazon_order_id,
    merchant_order_id,
    purchase_date as ori_purchase_time,
    substr(purchase_date,1,10)  AS purchase_date_part,
    substr(purchase_date,12,8)  AS purchase_time_part,
    substr(purchase_date,20,6)  as time_dirr_purchase,
    last_update_date as ori_last_update_time,
    substr(last_update_date,1,10)  AS last_update_date_part,
    substr(last_update_date,12,8)  AS last_update_time_part,
    substr(last_update_date,20,6)  as time_dirr_last,
    order_status,
    fulfillment_channel,
    sales_channel,
    order_channel,
    ship_service_level,
    product_name,
    sku as seller_sku,
    asin,
    item_status,
    cast(nvl(quantity,0) as bigint) as ordered_num,
    currency,
    cast(nvl(item_price              ,0) as decimal(18,6)) as item_amt,
    cast(nvl(item_tax                ,0) as decimal(18,6)) as item_tax,
    cast(nvl(shipping_price          ,0) as decimal(18,6)) as shipping_fee,
    cast(nvl(shipping_tax            ,0) as decimal(18,6)) as shipping_tax,
    cast(nvl(gift_wrap_price         ,0) as decimal(18,6)) as gift_wrap_fee ,
    cast(nvl(gift_wrap_tax           ,0) as decimal(18,6)) as gift_wrap_tax,
    cast(nvl(item_promotion_discount ,0) as decimal(18,6)) as item_promotion_discount,
    cast(nvl(ship_promotion_discount ,0) as decimal(18,6)) as ship_promotion_discount,
    ship_city,
    ship_state,
    ship_postal_code,
    ship_country,
    promotion_ids,
    cpf,
    case when is_business_order ='false' then 0
         when is_business_order ='true'  then 1
        end as is_business_order   ,
    purchase_order_number,
    price_designation,
    fulfilled_by,
    buyer_company_name,
    buyer_tax_registration_country,
    buyer_tax_registration_type,
    case when is_iba ='false' then 0
         when is_iba ='true'  then 1
        end as is_iba ,
    order_invoice_type,
    tenant_id
from  (SELECT id,
              case when report_type = '' then null else report_type end as report_type,
              case when seller_id = '' then null else seller_id end as seller_id,
              case when marketplace_id = '' then null else marketplace_id end as marketplace_id,
              case when report_id = '' then null else report_id end as report_id,
              case when start_date = '' then null else start_date end as start_date,
              case when end_date = '' then null else end_date end as end_date,
              case when data_last_update_time = '' then null else data_last_update_time end as data_last_update_time,
              case when amazon_order_id = '' then null else amazon_order_id end as amazon_order_id,
              case when merchant_order_id = '' then null else merchant_order_id end as merchant_order_id,
              case when purchase_date = '' then null else purchase_date end as purchase_date,
              case when last_updated_date = '' then null else last_updated_date end as last_update_date,
              case when order_status = '' then null else order_status end as order_status,
              case when fulfillment_channel = '' then null else fulfillment_channel end as fulfillment_channel,
              case when sales_channel = '' then null else sales_channel end as sales_channel,
              case when order_channel = '' then null else order_channel end as order_channel,
              case when ship_service_level = '' then null else ship_service_level end as ship_service_level,
              case when product_name = '' then null else product_name end as product_name,
              case when sku = '' then null else sku end as sku,
              case when asin = '' then null else asin end as asin,
              case when item_status = '' then null else item_status end as item_status,
              case when quantity = '' then null else quantity end as quantity,
              case when currency = '' then null else currency end as currency,
              case when item_price = '' then null else item_price end as item_price,
              case when item_tax = '' then null else item_tax end as item_tax,
              case when shipping_price = '' then null else shipping_price end as shipping_price,
              case when shipping_tax = '' then null else shipping_tax end as shipping_tax,
              case when gift_wrap_price = '' then null else gift_wrap_price end as gift_wrap_price,
              case when gift_wrap_tax = '' then null else gift_wrap_tax end as gift_wrap_tax,
              case when item_promotion_discount = '' then null else item_promotion_discount end as item_promotion_discount,
              case when ship_promotion_discount = '' then null else ship_promotion_discount end as ship_promotion_discount,
              case when ship_city = '' then null else ship_city end as ship_city,
              case when ship_state = '' then null else ship_state end as ship_state,
              case when ship_postal_code = '' then null else ship_postal_code end as ship_postal_code,
              case when ship_country = '' then null else ship_country end as ship_country,
              case when promotion_ids = '' then null else promotion_ids end as promotion_ids,
              case when cpf = '' then null else cpf end as cpf,
              case when is_business_order = '' then null else is_business_order end as is_business_order,
              case when purchase_order_number = '' then null else purchase_order_number end as purchase_order_number,
              case when price_designation = '' then null else price_designation end as price_designation,
              case when fulfilled_by = '' then null else fulfilled_by end as fulfilled_by,
              case when buyer_company_name = '' then null else buyer_company_name end as buyer_company_name,
              case when buyer_tax_registration_country = '' then null else buyer_tax_registration_country end as buyer_tax_registration_country,
              case when buyer_tax_registration_type = '' then null else buyer_tax_registration_type end as buyer_tax_registration_type,
              case when is_iba = '' then null else is_iba end as is_iba,
              case when order_invoice_type = '' then null else order_invoice_type end as order_invoice_type,
              case when tenant_id = '' then null else tenant_id end as tenant_id
       from whde.get_flat_file_all_orders_data_by_order_date_general
       where pt ='${bizdate}'
      )
;

---2.继续时间处理
drop table if exists temp2_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk;
create table if not exists temp2_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk
    lifecycle 1
as
select
    report_type,
    seller_id,
    marketplace_id,
    report_id,
    data_last_update_time ,
    amazon_order_id,
    merchant_order_id,
    ori_purchase_time,
    dateadd(to_date(concat_ws(' ',purchase_date_part,purchase_time_part),'yyyy-mm-dd hh:mi:ss'),+8,'hh') AS purchase_time,
    ori_last_update_time,
    dateadd(to_date(concat_ws(' ',last_update_date_part,last_update_time_part),'yyyy-mm-dd hh:mi:ss'),+8,'hh') AS last_update_time,
    order_status,
    fulfillment_channel,
    sales_channel,
    order_channel,
    ship_service_level,
    product_name,
    seller_sku,
    asin,
    item_status,
    ordered_num,
    currency,
    item_amt,
    item_tax,
    shipping_fee,
    shipping_tax,
    gift_wrap_fee ,
    gift_wrap_tax,
    item_promotion_discount,
    ship_promotion_discount,
    ship_city,
    ship_state,
    ship_postal_code,
    ship_country,
    promotion_ids,
    cpf,
    is_business_order,
    purchase_order_number,
    price_designation,
    fulfilled_by,
    buyer_company_name,
    buyer_tax_registration_country,
    buyer_tax_registration_type,
    is_iba,
    order_invoice_type,
    tenant_id,
    'adv_report'                                       as data_src   ,
    'get_flat_file_all_orders_data_by_order_date_general'               as table_src  ,
    '${bizdate}'                                       as data_dt    ,
    getdate()                                          as etl_data_dt
from temp1_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk
;

---3.去重逻辑
drop table if exists temp3_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk;
create table if not exists temp3_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk
    lifecycle 1
as
select
    report_type,
    seller_id,
    marketplace_id,
    report_id,
    data_last_update_time ,
    amazon_order_id,
    merchant_order_id,
    ori_purchase_time,
    purchase_time,
    ori_last_update_time,
    last_update_time,
    order_status,
    fulfillment_channel,
    sales_channel,
    order_channel,
    ship_service_level,
    product_name,
    seller_sku,
    asin,
    item_status,
    ordered_num,
    currency,
    item_amt,
    item_tax,
    shipping_fee,
    shipping_tax,
    gift_wrap_fee ,
    gift_wrap_tax,
    item_promotion_discount,
    ship_promotion_discount,
    ship_city,
    ship_state,
    ship_postal_code,
    ship_country,
    promotion_ids,
    cpf,
    is_business_order,
    purchase_order_number,
    price_designation,
    fulfilled_by,
    buyer_company_name,
    buyer_tax_registration_country,
    buyer_tax_registration_type,
    is_iba,
    order_invoice_type,
    tenant_id,
    data_src ,
    table_src  ,
    data_dt ,
    etl_data_dt,
    row_number() over (partition by seller_id,marketplace_id,amazon_order_id,merchant_order_id,ori_purchase_time,seller_sku,asin order by data_last_update_time desc) as rnk
from(
        select
            report_type,
            seller_id,
            marketplace_id,
            report_id,
            data_last_update_time ,
            amazon_order_id,
            merchant_order_id,
            ori_purchase_time,
            purchase_time,
            ori_last_update_time,
            last_update_time,
            order_status,
            fulfillment_channel,
            sales_channel,
            order_channel,
            ship_service_level,
            product_name,
            seller_sku,
            asin,
            item_status,
            ordered_num,
            currency,
            item_amt,
            item_tax,
            shipping_fee,
            shipping_tax,
            gift_wrap_fee ,
            gift_wrap_tax,
            item_promotion_discount,
            ship_promotion_discount,
            ship_city,
            ship_state,
            ship_postal_code,
            ship_country,
            promotion_ids,
            cpf,
            is_business_order,
            purchase_order_number,
            price_designation,
            fulfilled_by,
            buyer_company_name,
            buyer_tax_registration_country,
            buyer_tax_registration_type,
            is_iba,
            order_invoice_type,
            tenant_id,
            data_src ,
            table_src  ,
            data_dt ,
            etl_data_dt
        from temp2_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk
        union all
        select
            report_type,
            seller_id,
            marketplace_id,
            report_id,
            data_last_update_time ,
            amazon_order_id,
            merchant_order_id,
            ori_purchase_time,
            purchase_time,
            ori_last_update_time,
            last_update_time,
            order_status,
            fulfillment_channel,
            sales_channel,
            order_channel,
            ship_service_level,
            product_name,
            seller_sku,
            asin,
            item_status,
            ordered_num,
            currency,
            item_amt,
            item_tax,
            shipping_fee,
            shipping_tax,
            gift_wrap_fee ,
            gift_wrap_tax,
            item_promotion_discount,
            ship_promotion_discount,
            ship_city,
            ship_state,
            ship_postal_code,
            ship_country,
            promotion_ids,
            cpf,
            is_business_order,
            purchase_order_number,
            price_designation,
            fulfilled_by,
            buyer_company_name,
            buyer_tax_registration_country,
            buyer_tax_registration_type,
            is_iba,
            order_invoice_type,
            tenant_id,
            data_src ,
            table_src  ,
            data_dt ,
            etl_data_dt
        from  whde.dwd_amzn_all_orders_df
        where ds = '${bizdate2}'

    ) a
;
----插入
INSERT OVERWRITE TABLE whde.dwd_amzn_all_orders_df partition(ds = '${bizdate}')
select
    report_type,
    seller_id,
    a.marketplace_id,
    b.market_place_type,
    report_id,
    data_last_update_time ,
    amazon_order_id,
    merchant_order_id,
    ori_purchase_time,
    purchase_time,
    ori_last_update_time,
    last_update_time,
    order_status,
    fulfillment_channel,
    sales_channel,
    order_channel,
    ship_service_level,
    product_name,
    seller_sku,
    asin,
    item_status,
    ordered_num,
    currency,
    item_amt,
    item_tax,
    shipping_fee,
    shipping_tax,
    gift_wrap_fee ,
    gift_wrap_tax,
    item_promotion_discount,
    ship_promotion_discount,
    ship_city,
    ship_state,
    ship_postal_code,
    ship_country,
    promotion_ids,
    cpf,
    is_business_order,
    purchase_order_number,
    price_designation,
    fulfilled_by,
    buyer_company_name,
    buyer_tax_registration_country,
    buyer_tax_registration_type,
    is_iba,
    order_invoice_type,
    tenant_id,
    data_src ,
    table_src  ,
    data_dt ,
    etl_data_dt
from temp3_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk a
         left outer join whde.dim_marketplace_info_df  b
                         on a.marketplace_id = b.market_place_id
where rnk = 1
;

---删除临时表
drop table if exists temp1_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk;
drop table if exists temp2_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk;
drop table if exists temp3_dwd_trd_ord_amazon_flat_file_all_orders_report_${bizdate}_dk;
