--@exclude_input=whde.amzn_sp_search_term_by_search_term_report
--odps sql
--********************************************************************--
--author:Ada
--create time:2024-04-06 00:35:43
--********************************************************************--

CREATE TABLE IF NOT EXISTS  whde.ods_amzn_sp_search_term_by_search_term_report(
     tenant_id STRING COMMENT '租户ID',
     profile_id STRING COMMENT '配置Id',
     market_place_id STRING COMMENT '站点id',
     report_id STRING COMMENT '报告Id',
     report_type STRING COMMENT '报告类型',
     seller_id STRING COMMENT '卖家ID',
     report_date DATETIME COMMENT '报告日期',
     data_last_update_time DATETIME COMMENT '亚马逊数据生产时间',
     country_code STRING COMMENT '国家编码',
     portfolio_id STRING COMMENT 'portfolioID',
     campaign_id STRING COMMENT '广告活动ID',
     campaign_name STRING COMMENT '广告活动名称',
     campaign_status STRING COMMENT '广告活动状态',
     campaign_budget_amt DECIMAL(18,6) COMMENT '广告活动预算',
    campaign_budget_type STRING COMMENT '广告活动预算类型',
    campaign_budget_currency_code STRING COMMENT '广告活动预算币种',
    ad_group_id STRING COMMENT '广告组ID',
    ad_group_name STRING COMMENT '广告组名称',
    keyword_id STRING COMMENT '关键词ID',
    keyword STRING COMMENT '关键词',
    keyword_type STRING COMMENT '关键词类型',
    keyword_bid DECIMAL(18,6) COMMENT '关键词竞价',
    match_type STRING COMMENT '匹配类型',
    targeting STRING COMMENT '投放词',
    ad_keyword_status STRING COMMENT '关键词状态.',
    search_term STRING COMMENT '搜索词',
    impressions BIGINT COMMENT '曝光量',
    clicks BIGINT COMMENT '点击量',
    cost_per_click DECIMAL(18,6) COMMENT '平均每次点击花费',
    click_through_rate DECIMAL(18,6) COMMENT '点击除以曝光',
    cost DECIMAL(18,6) COMMENT '花费',
    purchases_1d BIGINT COMMENT '广告点击后1天内发生的归因转化事件数量',
    purchases_7d BIGINT COMMENT '广告点击后7天内发生的归因转化事件数量',
    purchases_14d BIGINT COMMENT '广告点击后14天内发生的归因转化事件数量',
    purchases_30d BIGINT COMMENT '广告点击后30天内发生的归因转化事件数量',
    purchases_same_sku_1d BIGINT COMMENT '广告点击后1天内同sku发生的归因转化事件数量',
    purchases_same_sku_7d BIGINT COMMENT '广告点击后7天内同sku发生的归因转化事件数量',
    purchases_same_sku_14d BIGINT COMMENT '广告点击后14天内同sku发生的归因转化事件数量',
    purchases_same_sku_30d BIGINT COMMENT '广告点击后30天内同sku发生的归因转化事件数量',
    units_sold_clicks_1d BIGINT COMMENT '广告点击后的1天内订购的总单位数',
    units_sold_clicks_7d BIGINT COMMENT '广告点击后的7天内订购的总单位数',
    units_sold_clicks_14d BIGINT COMMENT '广告点击后的14天内订购的总单位数',
    units_sold_clicks_30d BIGINT COMMENT '广告点击后的30天内订购的总单位数',
    sales_1d DECIMAL(18,6) COMMENT '广告点击后的1天内订购的总销售额',
    sales_7d DECIMAL(18,6) COMMENT '广告点击后的7天内订购的总销售额',
    sales_14d DECIMAL(18,6) COMMENT '广告点击后的14天内订购的总销售额',
    sales_30d DECIMAL(18,6) COMMENT '广告点击后的30天内订购的总销售额',
    attributed_sales_same_sku_1d DECIMAL(18,6) COMMENT '广告点击后的1天内同sku订购的总销售额',
    attributed_sales_same_sku_7d DECIMAL(18,6) COMMENT '广告点击后的7天内同sku订购的总销售额',
    attributed_sales_same_sku_14d DECIMAL(18,6) COMMENT '广告点击后的14天内同sku订购的总销售额',
    attributed_sales_same_sku_30d DECIMAL(18,6) COMMENT '广告点击后的30天内同sku订购的总销售额',
    units_sold_same_sku_1d BIGINT COMMENT '广告点击后的1天内同sku订购的总单位数',
    units_sold_same_sku_7d BIGINT COMMENT '广告点击后的7天内同sku订购的总单位数',
    units_sold_same_sku_14d BIGINT COMMENT '广告点击后的14天内同sku订购的总单位数',
    units_sold_same_sku_30d BIGINT COMMENT '广告点击后的30天内同sku订购的总单位数',
    kindle_edition_normalized_pages_read_14d BIGINT COMMENT ' 广告点击后14天内归因的Kindle版标准化阅读页数',
    kindle_edition_normalized_pages_royalties_14d DECIMAL(18,6) COMMENT '点击广告后14天内归因的估计Kindle版标准化页面的预计版税',
    sales_other_sku_7d DECIMAL(18,6) COMMENT '广告点击后的7天内其他sku订购的总销售额',
    units_sold_other_sku_7d BIGINT COMMENT '广告点击后的7天内其他sku订购的总单位数',
    acos_clicks_7d DECIMAL(18,6) COMMENT '基于广告点击后7天内的购买情况计算的广告销售成本',
    acos_clicks_14d DECIMAL(18,6) COMMENT '基于广告点击后14天内的购买情况计算的广告销售成本',
    roas_clicks_7d DECIMAL(18,6) COMMENT '广告点击后7天内产生的购买所得到的广告支出回报率',
    roas_clicks_14d DECIMAL(18,6) COMMENT '广告点击后14天内产生的购买所得到的广告支出回报率',
    data_src STRING COMMENT '数据源名',
    table_src STRING COMMENT '来源表名',
    data_dt STRING COMMENT '数据日期',
    etl_data_dt DATETIME COMMENT '数据加载日期'
    )
    PARTITIONED BY (ds STRING)
    STORED AS ALIORC
    TBLPROPERTIES ('comment'='亚马逊sp广告搜索词报告')
    LIFECYCLE 30;

INSERT OVERWRITE TABLE ods_amzn_sp_search_term_by_search_term_report PARTITION (ds ='${bizdate}' )
SELECT
    COALESCE(tenant_id,''),
    COALESCE(profile_id,''),
    COALESCE(market_place_id,''),
    COALESCE(report_id,''),
    COALESCE(report_type,''),
    COALESCE(seller_id,''),
    to_date(report_date,'yyyy-mm-dd'),
    to_date(data_last_update_time, 'yyyy-MM-dd HH:mi:ss')data_last_update_time,
    COALESCE(country_code,''),
    COALESCE(portfolio_id,''),
    COALESCE(campaign_id,''),
    COALESCE(campaign_name,''),
    COALESCE(campaign_status,''),
    COALESCE(cast(campaign_budget_amount as DECIMAL (18,6)),0),
    COALESCE(campaign_budget_type,''),
    COALESCE(campaign_budget_currency_code,''),
    COALESCE(ad_group_id,''),
    COALESCE(ad_group_name,''),
    COALESCE(keyword_id,''),
    COALESCE(keyword,''),
    COALESCE(keyword_type,''),
    COALESCE(cast(keyword_bid as DECIMAL (18,6)),0),
    COALESCE(match_type,''),
    COALESCE(targeting,''),
    COALESCE(ad_keyword_status,''),
    COALESCE(search_term,''),
    COALESCE(cast(impressions as bigint),0),
    COALESCE(cast(clicks as bigint),0),
    COALESCE(cast(cost_per_click as DECIMAL (18,6)),0),
    COALESCE(cast(click_through_rate as DECIMAL (18,6)),0),
    COALESCE(cast(cost as DECIMAL (18,6)),0),
    COALESCE(cast(purchases_1d as bigint),0),
    COALESCE(cast(purchases_7d as bigint),0),
    COALESCE(cast(purchases_14d as bigint),0),
    COALESCE(cast(purchases_30d as bigint),0),
    COALESCE(cast(purchases_same_sku_1d as bigint),0),
    COALESCE(cast(purchases_same_sku_7d as bigint),0),
    COALESCE(cast(purchases_same_sku_14d as bigint),0),
    COALESCE(cast(purchases_same_sku_30d as bigint),0),
    COALESCE(cast(units_sold_clicks_1d as bigint),0),
    COALESCE(cast(units_sold_clicks_7d as bigint),0),
    COALESCE(cast(units_sold_clicks_14d as bigint),0),
    COALESCE(cast(units_sold_clicks_30d as bigint),0),
    COALESCE(cast(sales_1d as DECIMAL (18,6)),0),
    COALESCE(cast(sales_7d as DECIMAL (18,6)),0),
    COALESCE(cast(sales_14d as DECIMAL (18,6)),0),
    COALESCE(cast(sales_30d as DECIMAL (18,6)),0),
    COALESCE(cast(attributed_sales_same_sku_1d as DECIMAL (18,6)),0),
    COALESCE(cast(attributed_sales_same_sku_7d as DECIMAL (18,6)),0),
    COALESCE(cast(attributed_sales_same_sku_14d as DECIMAL (18,6)),0),
    COALESCE(cast(attributed_sales_same_sku_30d as DECIMAL (18,6)),0),
    COALESCE(cast(units_sold_same_sku_1d as bigint),0),
    COALESCE(cast(units_sold_same_sku_7d as bigint),0),
    COALESCE(cast(units_sold_same_sku_14d as bigint),0),
    COALESCE(cast(units_sold_same_sku_30d as bigint),0),
    COALESCE(cast(kindle_edition_normalized_pages_read_14d as bigint),0),
    COALESCE(cast(kindle_edition_normalized_pages_royalties_14d as DECIMAL (18,6)),0),
    COALESCE(cast(sales_other_sku_7d as DECIMAL (18,6)),0),
    COALESCE(cast(units_sold_other_sku_7d as BIGINT ),0),
    COALESCE(cast(acos_clicks_7d as DECIMAL (18,6)),0),
    COALESCE(cast(acos_clicks_14d as DECIMAL (18,6)),0),
    COALESCE(cast(roas_clicks_7d as DECIMAL (18,6)),0),
    COALESCE(cast(roas_clicks_14d as DECIMAL (18,6)),0),
    "adv_report" data_src,
    "amzn_sp_search_term_by_search_term_report" table_src,
    '${bizdate}' data_dt,
    GETDATE()  etl_data_dt
FROM
    (
        SELECT
            case when id = 'null' then null else id end as id ,
            case when store_id = 'null' then null else store_id end as store_id ,
            case when profile_id = 'null' then null else profile_id end as profile_id ,
            case when marketplace_id = 'null' then null else marketplace_id end as market_place_id ,
            case when report_id = 'null' then null else report_id end as report_id ,
            case when report_type = 'null' then null else report_type end as report_type ,
            case when report_date = 'null' then null else report_date end as report_date ,
            case when data_last_update_time = 'null' then null else data_last_update_time end as data_last_update_time ,
            case when seller_id = 'null' then null else seller_id end as seller_id ,
            case when tenant_id = 'null' then null else tenant_id end as tenant_id ,
            case when country_code = 'null' then null else country_code end as country_code ,
            case when portfolio_id = 'null' then null else portfolio_id end as portfolio_id ,
            case when campaign_name = 'null' then null else campaign_name end as campaign_name ,
            case when campaign_id = 'null' then null else campaign_id end as campaign_id ,
            case when campaign_status = 'null' then null else campaign_status end as campaign_status ,
            case when campaign_budget_amount = 'null' then null else campaign_budget_amount end as campaign_budget_amount ,
            case when campaign_budget_type = 'null' then null else campaign_budget_type end as campaign_budget_type ,
            case when campaign_budget_currency_code = 'null' then null else campaign_budget_currency_code end as campaign_budget_currency_code ,
            case when ad_group_name = 'null' then null else ad_group_name end as ad_group_name ,
            case when ad_group_id = 'null' then null else ad_group_id end as ad_group_id ,
            case when keyword_id = 'null' then null else keyword_id end as keyword_id ,
            case when keyword = 'null' then null else keyword end as keyword ,
            case when keyword_type = 'null' then null else keyword_type end as keyword_type ,
            case when keyword_bid = 'null' then null else keyword_bid end as keyword_bid ,
            case when match_type = 'null' then null else match_type end as match_type ,
            case when targeting = 'null' then null else targeting end as targeting ,
            case when ad_keyword_status = 'null' then null else ad_keyword_status end as ad_keyword_status ,
            case when search_term = 'null' then null else search_term end as search_term ,
            case when impressions = 'null' then null else impressions end as impressions ,
            case when clicks = 'null' then null else clicks end as clicks ,
            case when cost = 'null' then null else cost end as cost ,
            case when cost_per_click = 'null' then null else cost_per_click end as cost_per_click ,
            case when click_through_rate = 'null' then null else click_through_rate end as click_through_rate ,
            case when purchases_1d = 'null' then null else purchases_1d end as purchases_1d ,
            case when purchases_7d = 'null' then null else purchases_7d end as purchases_7d ,
            case when purchases_14d = 'null' then null else purchases_14d end as purchases_14d ,
            case when purchases_30d = 'null' then null else purchases_30d end as purchases_30d ,
            case when purchases_same_sku_1d = 'null' then null else purchases_same_sku_1d end as purchases_same_sku_1d ,
            case when purchases_same_sku_7d = 'null' then null else purchases_same_sku_7d end as purchases_same_sku_7d ,
            case when purchases_same_sku_14d = 'null' then null else purchases_same_sku_14d end as purchases_same_sku_14d ,
            case when purchases_same_sku_30d = 'null' then null else purchases_same_sku_30d end as purchases_same_sku_30d ,
            case when units_sold_clicks_1d = 'null' then null else units_sold_clicks_1d end as units_sold_clicks_1d ,
            case when units_sold_clicks_7d = 'null' then null else units_sold_clicks_7d end as units_sold_clicks_7d ,
            case when units_sold_clicks_14d = 'null' then null else units_sold_clicks_14d end as units_sold_clicks_14d ,
            case when units_sold_clicks_30d = 'null' then null else units_sold_clicks_30d end as units_sold_clicks_30d ,
            case when sales_1d = 'null' then null else sales_1d end as sales_1d ,
            case when sales_7d = 'null' then null else sales_7d end as sales_7d ,
            case when sales_14d = 'null' then null else sales_14d end as sales_14d ,
            case when sales_30d = 'null' then null else sales_30d end as sales_30d ,
            case when attributed_sales_same_sku_1d = 'null' then null else attributed_sales_same_sku_1d end as attributed_sales_same_sku_1d ,
            case when attributed_sales_same_sku_7d = 'null' then null else attributed_sales_same_sku_7d end as attributed_sales_same_sku_7d ,
            case when attributed_sales_same_sku_14d = 'null' then null else attributed_sales_same_sku_14d end as attributed_sales_same_sku_14d ,
            case when attributed_sales_same_sku_30d = 'null' then null else attributed_sales_same_sku_30d end as attributed_sales_same_sku_30d ,
            case when units_sold_same_sku_1d = 'null' then null else units_sold_same_sku_1d end as units_sold_same_sku_1d ,
            case when units_sold_same_sku_7d = 'null' then null else units_sold_same_sku_7d end as units_sold_same_sku_7d ,
            case when units_sold_same_sku_14d = 'null' then null else units_sold_same_sku_14d end as units_sold_same_sku_14d ,
            case when units_sold_same_sku_30d = 'null' then null else units_sold_same_sku_30d end as units_sold_same_sku_30d ,
            case when kindle_edition_normalized_pages_read_14d = 'null' then null else kindle_edition_normalized_pages_read_14d end as kindle_edition_normalized_pages_read_14d ,
            case when kindle_edition_normalized_pages_royalties_14d = 'null' then null else kindle_edition_normalized_pages_royalties_14d end as kindle_edition_normalized_pages_royalties_14d ,
            case when sales_other_sku_7d = 'null' then null else sales_other_sku_7d end as sales_other_sku_7d ,
            case when units_sold_other_sku_7d = 'null' then null else units_sold_other_sku_7d end as units_sold_other_sku_7d ,
            case when acos_clicks_7d = 'null' then null else acos_clicks_7d end as acos_clicks_7d ,
            case when acos_clicks_14d = 'null' then null else acos_clicks_14d end as acos_clicks_14d ,
            case when roas_clicks_7d = 'null' then null else roas_clicks_7d end as roas_clicks_7d ,
            case when roas_clicks_14d = 'null' then null else roas_clicks_14d end as roas_clicks_14d
                ,ROW_NUMBER() OVER (PARTITION BY tenant_id,profile_id,campaign_id,ad_group_id,keyword_id,search_term,report_date ORDER BY pt DESC ) AS rn
        FROM    whde.amzn_sp_search_term_by_search_term_report
        WHERE   pt ='${bizdate}'  --SUBSTR(ds,1,10) >= to_char(DATEADD(TO_DATE('${bizdate}','yyyymmddhh'),-3,'hh'),'yyyymmddhh')
    ) s
WHERE rn=1
;
