
CREATE TABLE IF NOT EXISTS whde.ods_amzn_sp_campaigns_by_campaign_placement_report (
    tenant_id STRING COMMENT '租户ID',
    profile_id STRING COMMENT '配置Id',
    report_id STRING COMMENT '报告Id',
    report_type STRING COMMENT '报告类型',
    seller_id STRING COMMENT '卖家ID',
    report_date DATETIME COMMENT '报告日期',
    data_last_update_time DATETIME COMMENT '亚马逊数据生产时间',
    country_code STRING COMMENT '国家编码',
    campaign_id STRING COMMENT '广告活动ID',
    campaign_name STRING COMMENT '广告活动名称',
    campaign_status STRING COMMENT '广告活动状态',
    campaign_budget_amt DECIMAL(18,6) COMMENT '广告活动预算',
    campaign_budget_type STRING COMMENT '广告活动预算类型',
    campaign_budget_currency_code STRING COMMENT '广告活动预算币种',
    campaign_bidding_strategy STRING COMMENT '广告活动竞价策略',
    placement_classification STRING COMMENT '广告位',
    impressions BIGINT COMMENT '曝光量',
    clicks BIGINT COMMENT '点击量',
    cost_per_click DECIMAL(18,6) COMMENT '平均每次点击花费',
    click_through_rate DECIMAL(18,6) COMMENT '点击除以曝光',
    cost DECIMAL(18,6) COMMENT '花费',
    purchases_1d BIGINT COMMENT '广告点击后1天内发生的归因转化事件数量',
    purchases_7d BIGINT COMMENT '广告点击后7天内发生的归因转化事件数量',
    purchases_14d BIGINT COMMENT '广告点击后14天内发生的归因转化事件数量',
    purchases_30d BIGINT COMMENT '广告点击后30天内发生的归因转化事件数量',
    purchases_same_sku_1d BIGINT COMMENT '广告点击后1天内同sku发生的归因转化事件数量',
    purchases_same_sku_7d BIGINT COMMENT '广告点击后7天内同sku发生的归因转化事件数量',
    purchases_same_sku_14d BIGINT COMMENT '广告点击后14天内同sku发生的归因转化事件数量',
    purchases_same_sku_30d BIGINT COMMENT '广告点击后30天内同sku发生的归因转化事件数量',
    units_sold_clicks_1d BIGINT COMMENT '广告点击后的1天内订购的总单位数',
    units_sold_clicks_7d BIGINT COMMENT '广告点击后的7天内订购的总单位数',
    units_sold_clicks_14d BIGINT COMMENT '广告点击后的14天内订购的总单位数',
    units_sold_clicks_30d BIGINT COMMENT '广告点击后的30天内订购的总单位数',
    sales_1d DECIMAL(18,6) COMMENT '广告点击后的1天内订购的总销售额',
    sales_7d DECIMAL(18,6) COMMENT '广告点击后的7天内订购的总销售额',
    sales_14d DECIMAL(18,6) COMMENT '广告点击后的14天内订购的总销售额',
    sales_30d DECIMAL(18,6) COMMENT '广告点击后的30天内订购的总销售额',
    attributed_sales_same_sku_1d DECIMAL(18,6) COMMENT '广告点击后的1天内同sku订购的总销售额',
    attributed_sales_same_sku_7d DECIMAL(18,6) COMMENT '广告点击后的7天内同sku订购的总销售额',
    attributed_sales_same_sku_14d DECIMAL(18,6) COMMENT '广告点击后的14天内同sku订购的总销售额',
    attributed_sales_same_sku_30d DECIMAL(18,6) COMMENT '广告点击后的30天内同sku订购的总销售额',
    units_sold_same_sku_1d BIGINT COMMENT '广告点击后的1天内同sku订购的总单位数',
    units_sold_same_sku_7d BIGINT COMMENT '广告点击后的7天内同sku订购的总单位数',
    units_sold_same_sku_14d BIGINT COMMENT '广告点击后的14天内同sku订购的总单位数',
    units_sold_same_sku_30d BIGINT COMMENT '广告点击后的30天内同sku订购的总单位数',
    kindle_edition_normalized_pages_read_14d BIGINT COMMENT ' 广告点击后14天内归因的Kindle版标准化阅读页数',
    kindle_edition_normalized_pages_royalties_14d DECIMAL(18,6) COMMENT '点击广告后14天内归因的估计Kindle版标准化页面的预计版税',
    data_src STRING COMMENT '数据源名',
    table_src STRING COMMENT '来源表名',
    data_dt STRING COMMENT '数据日期',
    etl_data_dt DATETIME COMMENT '数据加载日期'
    )
    PARTITIONED BY (ds STRING)
    STORED AS ALIORC
    TBLPROPERTIES ('comment'='亚马逊sp广告广告位报告（数据分析请用ds增量表）')
    LIFECYCLE 30;

INSERT OVERWRITE TABLE ods_amzn_sp_campaigns_by_campaign_placement_report PARTITION (ds)
SELECT      COALESCE(tenant_id,''),
            COALESCE(profile_id,''),
            COALESCE(report_id,''),
            COALESCE(report_type,''),
            COALESCE(seller_id,''),
            to_date(report_date,'yyyy-mm-dd'),
            to_date(data_last_update_time, 'yyyy-MM-dd HH:mi:ss')data_last_update_time,
            COALESCE(country_code,''),
            COALESCE(campaign_id,''),
            COALESCE(campaign_name,''),
            COALESCE(campaign_status,''),
            COALESCE(cast(campaign_budget_amount as DECIMAL (18,6)),0),
            COALESCE(campaign_budget_type,''),
            COALESCE(campaign_budget_currency_code,''),
            COALESCE(campaign_bidding_strategy,''),
            COALESCE(placement_classification,''),
            COALESCE(cast(impressions as bigint),0),
            COALESCE(cast(clicks as bigint),0),
            COALESCE(cast(cost_per_click as DECIMAL (18,6)),0),
            COALESCE(cast(click_through_rate as DECIMAL (18,6)),0),
            COALESCE(cast(cost as DECIMAL (18,6)),0),
            COALESCE(cast(purchases_1d as bigint),0),
            COALESCE(cast(purchases_7d as bigint),0),
            COALESCE(cast(purchases_14d as bigint),0),
            COALESCE(cast(purchases_30d as bigint),0),
            COALESCE(cast(purchases_same_sku_1d as bigint),0),
            COALESCE(cast(purchases_same_sku_7d as bigint),0),
            COALESCE(cast(purchases_same_sku_14d as bigint),0),
            COALESCE(cast(purchases_same_sku_30d as bigint),0),
            COALESCE(cast(units_sold_clicks_1d as bigint),0),
            COALESCE(cast(units_sold_clicks_7d as bigint),0),
            COALESCE(cast(units_sold_clicks_14d as bigint),0),
            COALESCE(cast(units_sold_clicks_30d as bigint),0),
            COALESCE(cast(sales_1d as DECIMAL (18,6)),0),
            COALESCE(cast(sales_7d as DECIMAL (18,6)),0),
            COALESCE(cast(sales_14d as DECIMAL (18,6)),0),
            COALESCE(cast(sales_30d as DECIMAL (18,6)),0),
            COALESCE(cast(attributed_sales_same_sku_1d as DECIMAL (18,6)),0),
            COALESCE(cast(attributed_sales_same_sku_7d as DECIMAL (18,6)),0),
            COALESCE(cast(attributed_sales_same_sku_14d as DECIMAL (18,6)),0),
            COALESCE(cast(attributed_sales_same_sku_30d as DECIMAL (18,6)),0),
            COALESCE(cast(units_sold_same_sku_1d as bigint),0),
            COALESCE(cast(units_sold_same_sku_7d as bigint),0),
            COALESCE(cast(units_sold_same_sku_14d as bigint),0),
            COALESCE(cast(units_sold_same_sku_30d as bigint),0),
            COALESCE(cast(kindle_edition_normalized_pages_read_14d as bigint),0),
            COALESCE(cast(kindle_edition_normalized_pages_royalties_14d as DECIMAL (18,6)),0),
            "adv_report" data_src,
            "amzn_sp_campaigns_by_campaign_placement_report" table_src,
            '${bizdate}' data_dt,
            GETDATE()  etl_data_dt,
            SUBSTR('${bizdate}',1,8)ds
FROM
    (
        SELECT  case when profile_id = 'null' then null else profile_id end as profile_id,
                case when report_id = 'null' then null else report_id end as report_id,
                case when report_type = 'null' then null else report_type end as report_type,
                case when report_date = 'null' then null else report_date end as report_date,
                case when data_last_update_time = 'null' then null else data_last_update_time end as data_last_update_time,
                case when seller_id = 'null' then null else seller_id end as seller_id,
                case when tenant_id = 'null' then null else tenant_id end as tenant_id,
                case when country_code = 'null' then null else country_code end as country_code,
                case when campaign_name = 'null' then null else campaign_name end as campaign_name,
                case when campaign_id = 'null' then null else campaign_id end as campaign_id,
                case when campaign_status = 'null' then null else campaign_status end as campaign_status,
                case when campaign_budget_amount = 'null' then null else campaign_budget_amount end as campaign_budget_amount,
                case when campaign_budget_type = 'null' then null else campaign_budget_type end as campaign_budget_type,
                case when campaign_rule_based_budget_amount = 'null' then null else campaign_rule_based_budget_amount end as campaign_rule_based_budget_amount,
                case when campaign_applicable_budget_rule_id = 'null' then null else campaign_applicable_budget_rule_id end as campaign_applicable_budget_rule_id,
                case when campaign_applicable_budget_rule_name = 'null' then null else campaign_applicable_budget_rule_name end as campaign_applicable_budget_rule_name,
                case when campaign_budget_currency_code = 'null' then null else campaign_budget_currency_code end as campaign_budget_currency_code,
                case when impressions = 'null' then null else impressions end as impressions,
                case when clicks = 'null' then null else clicks end as clicks,
                case when cost = 'null' then null else cost end as cost,
                case when spend = 'null' then null else spend end as spend,
                case when purchases_1d = 'null' then null else purchases_1d end as purchases_1d,
                case when purchases_7d = 'null' then null else purchases_7d end as purchases_7d,
                case when purchases_14d = 'null' then null else purchases_14d end as purchases_14d,
                case when purchases_30d = 'null' then null else purchases_30d end as purchases_30d,
                case when purchases_same_sku_1d = 'null' then null else purchases_same_sku_1d end as purchases_same_sku_1d,
                case when purchases_same_sku_7d = 'null' then null else purchases_same_sku_7d end as purchases_same_sku_7d,
                case when purchases_same_sku_14d = 'null' then null else purchases_same_sku_14d end as purchases_same_sku_14d,
                case when purchases_same_sku_30d = 'null' then null else purchases_same_sku_30d end as purchases_same_sku_30d,
                case when units_sold_clicks_1d = 'null' then null else units_sold_clicks_1d end as units_sold_clicks_1d,
                case when units_sold_clicks_7d = 'null' then null else units_sold_clicks_7d end as units_sold_clicks_7d,
                case when units_sold_clicks_14d = 'null' then null else units_sold_clicks_14d end as units_sold_clicks_14d,
                case when units_sold_clicks_30d = 'null' then null else units_sold_clicks_30d end as units_sold_clicks_30d,
                case when sales_1d = 'null' then null else sales_1d end as sales_1d,
                case when sales_7d = 'null' then null else sales_7d end as sales_7d,
                case when sales_14d = 'null' then null else sales_14d end as sales_14d,
                case when sales_30d = 'null' then null else sales_30d end as sales_30d,
                case when attributed_sales_same_sku_1d = 'null' then null else attributed_sales_same_sku_1d end as attributed_sales_same_sku_1d,
                case when attributed_sales_same_sku_7d = 'null' then null else attributed_sales_same_sku_7d end as attributed_sales_same_sku_7d,
                case when attributed_sales_same_sku_14d = 'null' then null else attributed_sales_same_sku_14d end as attributed_sales_same_sku_14d,
                case when attributed_sales_same_sku_30d = 'null' then null else attributed_sales_same_sku_30d end as attributed_sales_same_sku_30d,
                case when units_sold_same_sku_1d = 'null' then null else units_sold_same_sku_1d end as units_sold_same_sku_1d,
                case when units_sold_same_sku_7d = 'null' then null else units_sold_same_sku_7d end as units_sold_same_sku_7d,
                case when units_sold_same_sku_14d = 'null' then null else units_sold_same_sku_14d end as units_sold_same_sku_14d,
                case when units_sold_same_sku_30d = 'null' then null else units_sold_same_sku_30d end as units_sold_same_sku_30d,
                case when kindle_edition_normalized_pages_read_14d = 'null' then null else kindle_edition_normalized_pages_read_14d end as kindle_edition_normalized_pages_read_14d,
                case when kindle_edition_normalized_pages_royalties_14d = 'null' then null else kindle_edition_normalized_pages_royalties_14d end as kindle_edition_normalized_pages_royalties_14d,
                case when campaign_bidding_strategy = 'null' then null else campaign_bidding_strategy end as campaign_bidding_strategy,
                case when cost_per_click = 'null' then null else cost_per_click end as cost_per_click,
                case when click_through_rate = 'null' then null else click_through_rate end as click_through_rate,
                case when placement_classification = 'null' then null else placement_classification end as placement_classification
                ,ROW_NUMBER() OVER (PARTITION BY tenant_id,profile_id,campaign_id,placement_classification,report_date ORDER BY pt DESC ) AS rn
        FROM    whde.amzn_sp_campaigns_by_campaign_placement_report
        WHERE   pt = '${bizdate}'
    ) s
WHERE rn=1
;
